### PR TITLE
Generate json

### LINKED ISSUE #237: Provide a way to generate swagger json programatically
Right now it seems like the only way to get the json output from the swagger generator is by hitting the web api. This is not good if you need to generate documentation using a command line tool. One can work around it by hitting the web api and storing the results, but there should be an easier way.

### PR DESCRIPTION
**Pull request by vikstrous**
fixes #237, based on / includes #234 to use the json array diff fix

I created a new SwaggerBuilder that can evolve independently from the SwaggerService. We can eventually change the implementation such that SwaggerService uses SwaggerBuilder rather than the other way around, but this works for now.

### CODE REVIEW

**Comment by emicklei** [comment]
thank you for your contribution!

**Comment by emicklei** [comment]
"SwaggerService uses SwaggerBuilder " , I like that direction.  This will be the design for swagger 2.0 support in any case.

**Comment by emicklei** [comment]
looking back at what has been merged, I noticed that some of my comments were not processed yet.  I may change them myself later ( e.g removing the xtra test package, commenting the builder ...)

**Comment by vikstrous** [comment]
I don't think it's a good idea to remove the extra package. I was not able to test the package name prefix of the type without it. I had a bug related to that the first time I attempted to make Writes() work with arrays. And, yeah, sorry I forgot to comment the builder.

**Pull request merged**
