### PR TITLE
List available representations in 406 body

### LINKED ISSUE #434: Acceptable representations not listed in body of '406: Not Acceptable' responses
RFC 7231 says that the server *should* include a list of representations in the body of a 406 response: https://tools.ietf.org/html/rfc7231#section-6.5.6

Currently restful just says:
```
HTTP/1.1 406 Not Acceptable
Date: Sun, 24 May 2020 14:31:55 GMT
Content-Length: 19
Content-Type: text/plain; charset=utf-8

406: Not Acceptable
```
<details>
<summary>Test server</summary>

```
package main

import (
	"io"
	"log"
	"net/http"

	"github.com/emicklei/go-restful"
)

func main() {
	ws := new(restful.WebService)
	ws.Route(ws.GET("/hello").Produces("text/plain").To(hello))
	restful.Add(ws)
	log.Fatal(http.ListenAndServe(":8080", nil))
}

func hello(req *restful.Request, resp *restful.Response) {
	io.WriteString(resp, "world")
}

```
</details>

But the RFC doesn't have an opinion on what form that list should take. As restful already provides a text/plain body, I think it should be expended to include each of the route's produces, perhaps:
```
406: Not Acceptable

Acceptable: text/plain, application/json
```

If you agree with the above, I'm happy to do the work.

### PR DESCRIPTION
**Pull request by brackendawson**
Becasue RFC7231 says we should.

fixes #434

### CODE REVIEW

**Comment by brackendawson** [comment]
I chose to not remove duplicates from `available` because this is the last thing in `detectRoute()` and therefore there should be none?

**Comment by brackendawson** [comment]
Also was this supposed to test a 406 response? https://github.com/emicklei/go-restful/blob/8487208e17d772637e9b2c61c522427fdd2fe83d/web_service_test.go#L154

**Comment by emicklei** [comment]
> I chose to not remove duplicates from `available` because this is the last thing in `detectRoute()` and therefore there should be none?

please explain why not removing dups?

**Comment by brackendawson** [comment]
> please explain why not removing dups?

Because the Accept header is the last thing checked in the router, a valid path should not contain any duplicate media types. If it did then a successful call would fail.

It does look like the sort of thing that would get missed if another switch was added to the router after Accept. I can add deduplication if you like? It is only exposed in the error case.

**Pull request merged**
