### PR TITLE
Fix 415 HTTP errors for idempotent requests introduced in #170

### PR DESCRIPTION
**Pull request by wuub**
see #170 for comments

### CODE REVIEW

**Comment by wuub** [comment]
sorry for the accidental force push :(

**Comment by emicklei** [comment]
So if the request normally does not contain a body (entity) then the content-type check can be ommitted. 

I tried confirming this for the methods listed in the condition by interpreting the http spec. So did others http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

I am eager to fix this issue and perhaps this fix will help us for 90% of the cases. What if somebody defines 2 GET routes consuming two different content-types? With this fix, the first wins.

@dkolbly mentioned in Issue #170 that simply testing the CT header is not enough. But again, who is going to stream data using the idempotent methods.

**Comment by wuub** [comment]
I'm not 100% sure this is the best way to fix this in go-restful, the problem is tricky and caused by several interlocking behaviours that from my point of view are also a bit suspicious.  

>  What if somebody defines 2 GET routes consuming two different content-types? With this fix, the first wins.

Probably. But registering two GET endpoints with different consuming types is in itself a strange behaviour since almost no clients send Content-Type with get requests.  Different Accept: headers, should be handled correctly, sure, different Consumes, I'm not convinced :) 


TBH I think the best behaviour here should be:
a) not setting default Content-Type when client sent an empty body
b) treating `nil` Content-Type as an indication of empty body (entity) and allowing it implicitly 
c) always validating client-provided Content-Type, event if it's attached to an idempotent method with empty body (entity)


But such logic was difficult to implement, since I'm not very familiar with go-restful internals.

**Comment by dkolbly** [comment]
Yeah, my case was streaming `POST`.  I agree on GET having two routes with different Consumes seems a bit weird.

**Comment by emicklei** [comment]
new proposal:

```
// Return whether this Route can consume content with a type specified by mimeTypes (can be empty).
func (r Route) matchesContentType(mimeTypes string) bool {

	if len(r.Consumes) == 0 {
		// did not specify what it can consume ;  any media type (“*/*”) is assumed
		return true
	}

	if len(mimeTypes) == 0 {
		// idempotent methods with (most-likely or garanteed) empty content match missing Content-Type
		m := r.Method
		if m == "GET" || m == "HEAD" || m == "OPTIONS" || m == "DELETE" || m == "TRACE" {
			return true
		}
		// proceed with default
		mimeTypes = MIME_OCTET
	}
```

1) According to JSR311 (3.5) if Consumes or Produces is empty then process it like it was `*/*`
2) It adds the special case where the ContentType is missing (is empty). Then the idempotent method check is done.

@wuub 
a) there is no way to tell whether the body is empty (streaming)
b) no Content-Type means application/octet-stream. For certain methods the match process is continued.
c) realized

About the go-internals, the Route.matchesContentType is part of the candidate selection of Routes which also includes matching the Produces "annotation" with the Accept header.

I still feel that this is a compromise ; the idempotent method check allows clients to send requests with arbitrary data as long as they "forget" to send the Content-Type (and have a matching Produces).
This check is needed to satisfy e.g. testcase TestContentType415_Issue170

**Comment by wuub** [comment]
AFAICT  `if len(mimeTypes) == 0 {` wil never be true, unless you change https://github.com/emicklei/go-restful/blob/master/jsr311.go#L65 here

**Comment by emicklei** [comment]
yes , that is part of the proposal

**Comment by emicklei** [comment]
Agree, the request will probably provide some hints via Headers whether a body can be expected. I will merge my proposal and try to refine the solution

**Pull request merged**
