### PR TITLE
Fix EntityEncoder

### PR DESCRIPTION
**Pull request by stuart-warren**
Updates #128 
Fixes up wongak/go-restful @wongak - full credit to him
Rebases to master
Added terrible example

### CODE REVIEW

**Comment by emicklei** [comment]
thx, i will study his work and your changes this weekend.

**Comment by emicklei** [comment]
I am working on a slightly different design and implementation on another branch which I will share for comparison later.

**Comment by stuart-warren** [comment]
cool :+1:

**Comment by emicklei** [comment]
package restful
		
		import "encoding/json"
		
		type EntityReader interface {
			// Read a serialized version of the value from the request.
			// The Request may have a decompressing reader.
			Read(req *Request, v interface{}) error
		}
		
		type EntityWriter interface {
			// Write an serialized version of the value on the response.
			// The Response may have a compressing writer.
			Write(req *Request, resp *Response, v interface{}) error
		}
		
		type entityJSON struct{}
		
		// Read unmarshalls the value from JSON
		func (e entityJSON) Read(req *Request, v interface{}) error {
			decoder := json.NewDecoder(req.Request.Body)
			decoder.UseNumber()
			return decoder.Decode(v)
		}
		
		// Write marshalls the value to JSON and set the Content-Type Header.
		func (e entityJSON) Write(req *Request, resp *Response, v interface{}) error {
			if v == nil {
				// do not write a nil representation
				return nil
			}
			if resp.prettyPrint {
				// pretty output must be created and written explicitly
				output, err := json.MarshalIndent(v, " ", " ")
				if err != nil {
					return err
				}
				resp.Header().Set(HEADER_ContentType, MIME_JSON)
				_, err = resp.Write(output)
				return err
			}
			// not-so-pretty
			resp.Header().Set(HEADER_ContentType, MIME_JSON)
			return json.NewEncoder(resp).Encode(v)
		}

**Pull request closed without merging**
