### PR TITLE
Introducing the EntityEncoder type, to handle different entities

### PR DESCRIPTION
**Pull request by wongak**
In preparation for #105 (which might also be of interest for me), I'd suggest to create an Interface, which describes how Entities should be handled.

What do you think?

### CODE REVIEW

**Comment by mc-team** [comment]
are you planing to merge this request ?

**Comment by emicklei** [comment]
Yes, I intend to add this feature; it needs some work as it cannot be merged as is.

**Comment by emicklei** [comment]
Just to let any watchers know that I am working on getting feature in. The main change I am hoping to achieve is that each Encoder and Decoder (separate them?) is stateless.

**Comment by jchenry** [comment]
+1

**Comment by emicklei** [comment]
package restful
		
		import "encoding/json"
		
		type EntityReader interface {
			// Read a serialized version of the value from the request.
			// The Request may have a decompressing reader.
			Read(req *Request, v interface{}) error
		}
		
		type EntityWriter interface {
			// Write an serialized version of the value on the response.
			// The Response may have a compressing writer.
			Write(req *Request, resp *Response, v interface{}) error
		}
		
		type entityJSON struct{}
		
		// Read unmarshalls the value from JSON
		func (e entityJSON) Read(req *Request, v interface{}) error {
			decoder := json.NewDecoder(req.Request.Body)
			decoder.UseNumber()
			return decoder.Decode(v)
		}
		
		// Write marshalls the value to JSON and set the Content-Type Header.
		func (e entityJSON) Write(req *Request, resp *Response, v interface{}) error {
			if v == nil {
				// do not write a nil representation
				return nil
			}
			if resp.prettyPrint {
				// pretty output must be created and written explicitly
				output, err := json.MarshalIndent(v, " ", " ")
				if err != nil {
					return err
				}
				resp.Header().Set(HEADER_ContentType, MIME_JSON)
				_, err = resp.Write(output)
				return err
			}
			// not-so-pretty
			resp.Header().Set(HEADER_ContentType, MIME_JSON)
			return json.NewEncoder(resp).Encode(v)
		}

**Comment by emicklei** [comment]
This is taken from an older local branch. 

The idea is to have 2 interfaces allowing different structs to implement the Read and Write. The Read requires a Request and a value to populate. If it fails it returns with an error. Write an error response will happen in the container.

The Write requires both a Request and a Response with the value. The writing implementation may need additional information from the Request. The example implementation here reflects that of the current one in Response. (that's why there is pretty handling).

Just like the proposal for @wongak , there needs to be a way to register readers and writers (i call them like this because the R,R has a ReadEntity and WriteEntity respectively). 

Finding out what MIME to read is done in the Request. The MIME to write in the Response which is determined by looking at the Header and Defaults.

Although I did not write the XML version, I guess that it will be possible to define one with this interface. The bigger question is whether these interface suffice for the encodings you have in mind (application/x-protobuf, text/csv, etc.).

Please comment on this proposal.

**Comment by stuart-warren** [comment]
Looks alright to me :+1:

**Comment by emicklei** [comment]
i just push the branch for this feature. https://github.com/emicklei/go-restful/tree/entityplug

**Comment by emicklei** [comment]
Please verify the current implementation in the entityplug branch. I am about to merge this into the master.

**Comment by emicklei** [comment]
The entityplug branch has been merged into the branch.

**Pull request closed without merging**
