### PR TITLE
experiment in adding optional magic

### PR DESCRIPTION
**Pull request by vikstrous**
Do not merge this as it is. This is an experiment I did in adding some optional magic. I want to see what people think about this. Is it useful? Is it too specific? Do the function signatures make sense?

I haven't written `typeIsRequestFunc` yet, but I think you can imagine what that would look like.

The basic idea is to use `.Magic()` instead of `.To()` and have the router handle the boilerplate for reading and writing responses. This does not replace `To` because it can't handle more advanced use cases, but I think it would be nice to have.

### CODE REVIEW

**Comment by emicklei** [comment]
I will have a look at the code and think about this idea. Thanks

**Comment by nathanejohnson** [comment]
This is kind of interesting.  So is the main point of this to take the pain away from unmarshaling data into generic structs and handle errors consistently?  If so, I ended up doing something that handles unmarshaling request bodies with a filter.  Here is an example

    // This function returns a go-restful filter function that unmarshals data from a POST or PUT body
    // into a value of type DataType, then stores the resulting value in a request attribute
    // with name "name".  This allocates a new variable the same type as DataType on your behalf.
    // DataType is never read or modified outside of inspecting its type, so it is not a requirement
    // that an allocated variable be passed in.  Because of this, passing (*Foo)(nil) is valid,
    // and the attribute will point to an allocated instance of Foo populated with input.
    //
    // Valid DataType types are are structs and pointers to structs.  If you pass a struct, the attribute
    // will be a struct, if you pass a pointer, the attribute will be a pointer to the struct.  If a bad
    // DataType is passed in, a runtime panic will be generated.  In case of an error when calling
    // ReadEntity, returns a bad request error and stops the chain.
    //
    // Example:
    //
    //		ws.Route(ws.POST("/foo").
    //			To(inst.CreateFoo).
    //			Reads(Foo{}).
    //			Doc("Create a foo record").
    //			Filter(this.UnmarshalBodyFilter((*Foo)(nil), "foo")).
    //			Writes(ResponseStatus{}))
    //
    //		func (inst *Instance) CreateFoo(req *restful.Request, resp *restful.Response) {
    //			foo := req.Attribute("foo").(*Foo)
    //			// if we get here, foo is guaranteed to be non-nil
    //			// do useful stuff
    //		}
    func (this *Instance) UnmarshalBodyFilter(DataType interface{}, name string) restful.FilterFunction {
    	return func(req *restful.Request, resp *restful.Response, chain *restful.FilterChain) {
    		// A bunch of code to make sure we don't deref a nil pointer or other accidental panic,
    		// instead sending our own custom awesome panic.  Don't panic!
    		dtType := reflect.TypeOf(DataType)
    		if dtType == nil {
    			panic("nil passed as DataType to UnmarshalBodyFilter")
    		}
    
    		dtOrigType := dtType
    		wantsPtr := false
    
    		// Check to see if this DataType is a pointer, if so deref once
    		if dtType.Kind() == reflect.Ptr {
    			dtType = dtType.Elem()
    			wantsPtr = true
    		}
    
    		// Ensure this is a struct
    		if dtType.Kind() != reflect.Struct {
    			panic(fmt.Sprintf("Invalid DataType passed to UnmarshalBodyFilter: %s",
    				dtOrigType.Kind().String()))
    		}
    
    		// Now we get down to business of being marginally useful.
    		// Allocate a new struct
    		data := reflect.New(dtType)
    
    		// Unmarshal / decode
    		err := req.ReadEntity(data.Interface())
    
    		// All this work just for consistent error handling...
    		if err != nil {
    			errorBadRequest.WriteStatus(resp, err.Error())
    			return
    		}
    
    		// Success!
    		// data represents a pointer value, so figure out what to do
    		if wantsPtr {
    			req.SetAttribute(name, data.Interface())
    		} else {
    			req.SetAttribute(name, data.Elem().Interface())
    		}
    		this.Log.Debug("received data: \n%#v", req.Attribute(name))
    
    		chain.ProcessFilter(req, resp)
    	}
    }

**Comment by vikstrous** [comment]
Considering that the whole point of this framework is to not have magic, I like your filter approach. I would go a little further and say that it should be possible to know the type of the request from the `Reads()` documentation and the name of the body struct should always be the same. Then this filter can be applied globally with no arguments.

Writing this magic unmarshalling filter would require access to the Route in the filter https://github.com/emicklei/go-restful/issues/236

Maybe this filter can be provided by go-restful and be trivial to optionally include your app in one line.

**Comment by vikstrous** [comment]
One thing that's awkward with both of our approaches is that the error to return in case of input parsing failure can't be customized. We might need better error reporting infrastructure to go along with this input parser. Maybe something like what I proposed above might work. I don't have a specific implementation in mind yet. I'll open a separate issue for that.

**Comment by emicklei** [comment]
i guess this work is no longer of interest to you, close it?

**Pull request closed without merging**
