### PR TITLE
no request content cache in v2

### PR DESCRIPTION
**Pull request by AdoHe**
@emicklei According to what we have talked  here #306, I open this PR to disable request content cache, I want to make sure this is just what we want, then I will add an example to show how we can implement the same with filter. PTAL. Besides should we create a new v2 branch, or we just use master branch?

### CODE REVIEW

**Comment by emicklei** [comment]
I think it is a good idea to put these changes in its own branch

**Comment by AdoHe** [comment]
@emicklei sorry I am not very clear, what you mean in its own branch?

**Comment by emicklei** [comment]
let's create a branch called "v2" and collect the related changes there

**Comment by emicklei** [comment]
i am going to repeat this change to the current master.

**Comment by AdoHe** [comment]
@emicklei should I open a PR based on master?

**Comment by emicklei** [comment]
@AdoHe I already applied the same changes to the current master. Thanks. Would you be interested in working on swagger2?

**Comment by AdoHe** [comment]
@emicklei I just return from my ooo, will we start working on swagger2 in this year?

**Comment by emicklei** [comment]
yes, swagger2 in on my hot list.  It has been a while since I paid attention to it. Partly because of the decision whether or not to embrace go-swagger pkg.

**Pull request closed without merging**
